service: step-function-demo

custom:

provider:
  name: aws
  runtime: nodejs6.10
  stage: stg
  region: ap-northeast-1
  timeout: 30

functions:
  addNumber:
    handler: app.addNumber

stepFunctions:
  stateMachines:
    addDemo:
      name: addDemo
      definition:
        Comment: "An add demo"
        StartAt: AddNumber
        States:
          AddNumber:
            Type: Task
            Resource: arn:aws:lambda:#{AWS::Region}:#{AWS::AccountId}:function:${self:service}-${opt:stage}-addNumber
            End: true
    waitDemo:
      name: waitDemo
      definition:
        Comment: "An wait demo"
        StartAt: Wait10s
        States:
          Wait10s:
            Type: Wait
            Seconds: 10
            End: true

plugins:
  - serverless-step-functions
  - serverless-pseudo-parameters
